# Generated by Django 5.1.2 on 2024-12-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='-', max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='user', max_length=255, unique=True, verbose_name='username'),
        ),
    ]
