# Generated by Django 5.1.2 on 2025-01-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_owner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_sold_or_rented',
            field=models.BooleanField(default=False),
        ),
    ]
